version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./react-docker
    ports:
      - "3000:3000"
    container_name: react-docker
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/react-docker
       - /usr/src/app/my-app/node_modules        